export const CARD_DRAW_SUCCESS = 'CARD_DRAW_SUCCESS'

export const OCCUPIE_TILE = 'OCCUPIE_TILE'
export const OCCUPIE_TILE_SUCCESS = 'OCCUPIE_TILE_SUCCESS'
export const OCCUPIE_CONFIRM_SUCCESS = 'OCCUPIE_CONFIRM_SUCCESS'
export const OCCUPIE_CANCEL_SUCCESS = 'OCCUPIE_CANCEL_SUCCESS'